.TH GRIDGUESS 1 gridguess\-VERSION
.SH NAME
gridguess \- classroom board game
.SH SYNOPSIS
.SY gg
.I file
.YS
.SH DESCRIPTION
.BR gridguess (1)
is a classroom board game designed to be both fun and easy to prepare for
educators with any level of technical skill.  It functions on a grid of unknown
questions with corresponding answers hidden behind question point values.  Each
board is defined by a formatted text file.
.PP
The board file must be typed accurately as it has a very strict format.  
.BR gridguess (1)
will return a diagnostic error message with the line number when it encounters
a formatting error.  The format details can be found in
.BR gridguess "(5). "
.TP
Newline Expected
Given if a newline was expected rather than another slot entry, or at the end
of the file if the last column was not ended with an extra newline.
.TP
Newline or Row Expected
Given if the file terminates abruptly without ending its final column entry
with a newline.
.TP
Title Expected
Given if the input file is empty.
.TP
End of File Expected
Given if there are more than six columns.
.BR gridguess (1)
will not attempt to parse more than it can fit on a board, it will simply
terminate execution.
.TP
Delimeters not Found
Given if a column entry is not properly delimited with "
.B  %% 
".
.SH AUTHOR
Written by FearlessDoggo21.
.SH SEE ALSO
.BR gridguess (5)
